-- Create goods_exits table
create table if not exists public.goods_exits (
    id uuid default gen_random_uuid() primary key,
    sequential_id bigint generated by default as identity,
    destination_farm_id uuid references public.fazendas(id) not null,
    driver_name text not null,
    exit_date timestamptz not null default now(),
    created_by uuid references public.usuarios(id),
    observation text,
    created_at timestamptz default now()
);

-- Add fk to goods_receipts
alter table public.goods_receipts 
add column if not exists exit_id uuid references public.goods_exits(id);

-- RLS for goods_exits
alter table public.goods_exits enable row level security;

create policy "Allow application access goods_exits"
on public.goods_exits
for all
using (true)
with check (true);

-- Optional: Migrate existing data (Best effort)
-- We insert into goods_exits based on distinct exit_at/farm/driver in goods_receipts
-- This is a bit complex to do perfectly in SQL without PL/pgSQL for linking back, 
-- so we will just create the table and let new data use it properly. 
-- Old data will remain displayed as "Legacy" or we can manually fix if needed.
-- However, for the 'Exit List' to show old items, we might need to backfill. 
-- For now, let's start fresh or assume user will re-dispatch if testing.
