-- Migration: Alterar TODAS as policies de 'public' para 'authenticated'

ALTER POLICY "Todos podem ler funções" ON public."funcoes" TO authenticated;
ALTER POLICY "Todos podem ler fazendas" ON public."fazendas" TO authenticated;
ALTER POLICY "Usuários podem ver itens de suas solicitações" ON public."itens_solicitacao" TO authenticated;
ALTER POLICY "Allow Public Read" ON public."system_parameters" TO authenticated;
ALTER POLICY "Todos podem ver" ON public."cleaning_registries" TO authenticated;
ALTER POLICY "odp_sel" ON public."out_of_deadline_payments" TO authenticated;
ALTER POLICY "odp_mod" ON public."out_of_deadline_payments" TO authenticated;
ALTER POLICY "Postos Select" ON public."postos" TO authenticated;
ALTER POLICY "Abastecimentos Select" ON public."abastecimentos" TO authenticated;
ALTER POLICY "Todos podem ver fornecedores" ON public."unisystem_suppliers" TO authenticated;
ALTER POLICY "Todos podem ver notas unisystem" ON public."unisystem_invoices" TO authenticated;
ALTER POLICY "is_sel_admin_only" ON public."integration_settings" TO authenticated;
ALTER POLICY "Permitir leitura baseada na solicitação pai" ON public."itens_solicitacao" TO authenticated;
ALTER POLICY "Acesso pcm_solicitacoes_compras" ON public."pcm_solicitacoes_compras" TO authenticated;
ALTER POLICY "Insert pcm_solicitacoes_compras" ON public."pcm_solicitacoes_compras" TO authenticated;
ALTER POLICY "Update pcm_solicitacoes_compras" ON public."pcm_solicitacoes_compras" TO authenticated;
ALTER POLICY "Acesso late_payments" ON public."late_payments" TO authenticated;
ALTER POLICY "Insert late_payments" ON public."late_payments" TO authenticated;
ALTER POLICY "Update late_payments" ON public."late_payments" TO authenticated;
ALTER POLICY "Visualização global de usuários" ON public."usuarios" TO authenticated;
ALTER POLICY "Admins editam usuários" ON public."usuarios" TO authenticated;
ALTER POLICY "core_select_all" ON public."fazendas" TO authenticated;
ALTER POLICY "Permitir exclusão pelo dono ou admin" ON public."direct_receipts" TO authenticated;
ALTER POLICY "Permitir leitura baseada no escopo" ON public."solicitacoes" TO authenticated;
ALTER POLICY "Permitir inserção" ON public."solicitacoes" TO authenticated;
ALTER POLICY "Permitir atualização" ON public."solicitacoes" TO authenticated;
ALTER POLICY "Permitir exclusão" ON public."solicitacoes" TO authenticated;
ALTER POLICY "Permitir leitura baseada no escopo PCM" ON public."pcm_solicitacoes_compras" TO authenticated;
ALTER POLICY "Permitir inserção PCM" ON public."pcm_solicitacoes_compras" TO authenticated;
ALTER POLICY "Permitir atualização PCM" ON public."pcm_solicitacoes_compras" TO authenticated;
ALTER POLICY "Permitir inserção baseada na solicitação pai" ON public."itens_solicitacao" TO authenticated;
ALTER POLICY "Permitir atualização baseada na solicitação pai" ON public."itens_solicitacao" TO authenticated;
ALTER POLICY "Permitir exclusão baseada na solicitação pai" ON public."itens_solicitacao" TO authenticated;
ALTER POLICY "Permitir exclusão PCM" ON public."pcm_solicitacoes_compras" TO authenticated;
ALTER POLICY "Permitir leitura abastecimentos" ON public."abastecimentos" TO authenticated;
ALTER POLICY "Permitir inserção abastecimentos" ON public."abastecimentos" TO authenticated;
ALTER POLICY "Permitir atualização abastecimentos" ON public."abastecimentos" TO authenticated;
ALTER POLICY "Permitir exclusão abastecimentos" ON public."abastecimentos" TO authenticated;
ALTER POLICY "Permitir leitura veiculos" ON public."veiculos" TO authenticated;
ALTER POLICY "Permitir mod veiculos" ON public."veiculos" TO authenticated;
ALTER POLICY "core_mod_admin" ON public."fazendas" TO authenticated;
ALTER POLICY "core_select_all_func" ON public."funcoes" TO authenticated;
ALTER POLICY "core_mod_admin_func" ON public."funcoes" TO authenticated;
ALTER POLICY "audit_select" ON public."audit_logs" TO authenticated;
ALTER POLICY "mat_sel" ON public."materials" TO authenticated;
ALTER POLICY "mat_mod" ON public."materials" TO authenticated;
ALTER POLICY "gr_sel" ON public."goods_receipts" TO authenticated;
ALTER POLICY "gr_mod" ON public."goods_receipts" TO authenticated;
ALTER POLICY "ge_sel" ON public."goods_exits" TO authenticated;
ALTER POLICY "ge_mod" ON public."goods_exits" TO authenticated;
ALTER POLICY "dr_sel" ON public."direct_receipts" TO authenticated;
ALTER POLICY "dr_mod" ON public."direct_receipts" TO authenticated;
ALTER POLICY "sd_sel" ON public."station_drainages" TO authenticated;
ALTER POLICY "sd_mod" ON public."station_drainages" TO authenticated;
ALTER POLICY "cl_sel" ON public."cleaning_registries" TO authenticated;
ALTER POLICY "cl_mod" ON public."cleaning_registries" TO authenticated;
ALTER POLICY "lp_sel" ON public."late_payments" TO authenticated;
ALTER POLICY "lp_mod" ON public."late_payments" TO authenticated;
ALTER POLICY "cat_postos_mod" ON public."postos" TO authenticated;
ALTER POLICY "sv_sel" ON public."savings" TO authenticated;
ALTER POLICY "sv_mod" ON public."savings" TO authenticated;
ALTER POLICY "pi_sel" ON public."pending_invoices" TO authenticated;
ALTER POLICY "pi_mod" ON public."pending_invoices" TO authenticated;
ALTER POLICY "cat_postos_sel" ON public."postos" TO authenticated;
ALTER POLICY "cat_supp_sel" ON public."suppliers" TO authenticated;
ALTER POLICY "cat_supp_mod" ON public."suppliers" TO authenticated;
ALTER POLICY "cat_veic_sel" ON public."veiculos" TO authenticated;
ALTER POLICY "cat_veic_mod" ON public."veiculos" TO authenticated;
ALTER POLICY "cat_us_sel" ON public."unisystem_suppliers" TO authenticated;
ALTER POLICY "cat_us_mod" ON public."unisystem_suppliers" TO authenticated;
ALTER POLICY "sp_sel" ON public."system_parameters" TO authenticated;
ALTER POLICY "sp_mod" ON public."system_parameters" TO authenticated;
ALTER POLICY "is_mod" ON public."integration_settings" TO authenticated;
ALTER POLICY "tl_sel" ON public."system_timeline" TO authenticated;
ALTER POLICY "tl_mod" ON public."system_timeline" TO authenticated;
ALTER POLICY "isa_sel" ON public."itens_solicitacao" TO authenticated;
ALTER POLICY "isa_mod" ON public."itens_solicitacao" TO authenticated;
ALTER POLICY "sxa_sel" ON public."solicitacao_anexos" TO authenticated;
ALTER POLICY "sxa_mod" ON public."solicitacao_anexos" TO authenticated;
ALTER POLICY "usd_cat_sel" ON public."used_items_catalog" TO authenticated;
ALTER POLICY "usd_cat_mod" ON public."used_items_catalog" TO authenticated;
ALTER POLICY "usd_stk_sel" ON public."used_items_stock" TO authenticated;
ALTER POLICY "usd_stk_mod" ON public."used_items_stock" TO authenticated;
ALTER POLICY "usd_trx_sel" ON public."used_items_transactions" TO authenticated;
ALTER POLICY "usd_trx_mod" ON public."used_items_transactions" TO authenticated;
ALTER POLICY "nit_sel" ON public."nuntec_ignored_transfers" TO authenticated;
ALTER POLICY "nit_mod" ON public."nuntec_ignored_transfers" TO authenticated;
ALTER POLICY "ui_sel" ON public."unisystem_invoices" TO authenticated;
ALTER POLICY "ui_mod" ON public."unisystem_invoices" TO authenticated;
ALTER POLICY "odps_sel" ON public."out_of_deadline_payment_sectors" TO authenticated;
ALTER POLICY "odps_mod" ON public."out_of_deadline_payment_sectors" TO authenticated;
ALTER POLICY "odpu_sel" ON public."out_of_deadline_payment_units" TO authenticated;
ALTER POLICY "odpu_mod" ON public."out_of_deadline_payment_units" TO authenticated;
ALTER POLICY "sr_sel" ON public."stock_requests" TO authenticated;
ALTER POLICY "sr_mod" ON public."stock_requests" TO authenticated;
ALTER POLICY "sri_sel" ON public."stock_request_items" TO authenticated;
ALTER POLICY "sri_mod" ON public."stock_request_items" TO authenticated;
